### ISSUE TITLE
Exception when using data bags that don't exist

### ISSUE THREAD

**Issue by gkaizer1** [poise/poise-hoist#2]
** INFO: *** Chef 12.17.44 ***
Seems like with version 1.2.0 the following error was introduced:

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/poise-hoist/files/halite_gem/poise_hoist.rb:44:in `hoist!'
  /var/chef/cache/cookbooks/poise-hoist/files/halite_gem/poise_hoist/cheftie.rb:19:in `<top (required)>'
  /var/chef/cache/cookbooks/poise-hoist/libraries/default.rb:19:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/poise-hoist/files/halite_gem/poise_hoist.rb:

 37:      # Don't continue if we aren't using policies.
 38:      return unless policy_group
 39:      Chef::Log.debug("Running attribute Hoist for group #{policy_group}")
 40:      # Hoist away, mateys!
 41:      Chef::Mixin::DeepMerge.hash_only_merge!(node.role_default, node.role_default[policy_group]) if node.role_default.include?(policy_group)
 42:      Chef::Mixin::DeepMerge.hash_only_merge!(node.role_override, node.role_override[policy_group]) if node.role_override.include?(policy_group)
 43:      # Grab from a data bag if one is configured.
 44>>     hoist_from_data_bag!(node, policy_group, node['poise-hoist']['data_bag']) if node['poise-hoist']['data_bag']
 45:      # Install the patch for chef_environment.
 46:      patch_chef_environment!(node, policy_group)
 47:    end
 48:
 49:    # Pull attribute data in from a data bag. Checks for an item matching the
 50:    # node node, and then the policy group.
 51:    #
 52:    # @api private
 53:    # @param node [Chef::Node] Node object to modify.

**Comment by aroxby** [comment]
+1
Also seeing this error.  I'm not using data bags but I suspect one of my dependencies is.

**Comment by duekiller** [comment]
I am using Chef 12.17.44

**Comment by coderanger** [comment]
New release will be out shortly, once CI catches up a bit.

**Comment by coderanger** [comment]
Fixed in version 1.2.1. Thanks for the report!
